server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/lehrerkalender_springboot?useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: Lehrerkalender

  mail:
    host: smtp.gmail.com
    port: 587
    username: wooddiidev@gmail.com
    password: advmctrsoxezovcy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


